### PR TITLE
Make the Memory Map nicer

### PR DESCRIPTION
**Pull request by Dudejoe870**
Just makes it a bit easier to add stuff to, and maybe even _slightly_ more efficient, but also could be slightly slower, I don't know, someone would have to test that.

### CODE REVIEW

**Comment by bachimusprime** [comment]
*MemoryEntries

**Comment by Dudejoe870** [comment]
Oh yeah sorry for the spelling mistake, I'll go ahead and fix it.

**Comment by bachimusprime** [comment]
You REALLY need to be using special memory access handlers for the I/O registers.

**Comment by Dudejoe870** [comment]
Well I'd figure that'd give me the ability to mirror certain places in memory into others, which is handy for this, as there's lots of that involved.

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
I'll check this out and review it, thanks!

**Comment by Dudejoe870** [comment]
With the way that you're doing IO Handling now, how are you gonna handle Writes to IO Memory? @Cyuubi

**Comment by Dudejoe870** [comment]
Okay, well I just tested the master build, apparently the way I implemented something was wrong, I'll go ahead and start debugging it.

**Comment by bachimusprime** [comment]
lgtm

**Comment by Dudejoe870** [comment]
Well, when I tested it, it didn't do the same thing as the Master Branch, which was the goal, so I am currently working on fixing it, just figured out what's wrong, just gotta figure out how to fix it.

**Comment by Dudejoe870** [comment]
The new Commit should have it working?  It doesn't do the exact same thing as Master, but it seems to do what it's supposed to do?  I have no idea, someone will really have to test it.

**Comment by bachimusprime** [comment]
yeah that looks like it should work

**Comment by Dudejoe870** [comment]
Okay well, I'm basically done, so @Cyuubi can review it whenever she gets time.

**Comment by Dudejoe870** [comment]
Closing this as there's a big update coming and this will be outdated very soon.

**Pull request closed without merging**
